---
title: "git_01"
author: "Leticia Estrella"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,   
 And the mome raths outgrabe.   

“Beware the Jabberwock, my son!   
 The jaws that bite, the claws that catch!   
Beware the Jubjub bird, and shun   
The frumious Bandersnatch!”   

## Second Verse
He took his vorpal sword in hand;   
Long time the manxome foe he sought—   
So rested he by the Tumtum tree   
And stood awhile in thought.   
And, as in uffish thought he stood,   
The Jabberwock, with eyes of flame,   
Came whiffling through the tulgey wood,   
And burbled as it came!   

## Third Verse
One, two! One, two! And through and through   
The vorpal blade went snicker-snack!   
He left it dead, and with its head   
He went galumphing back.   
“And hast thou slain the Jabberwock?   
Come to my arms, my beamish boy!   
O frabjous day! Callooh! Callay!”   
He chortled in his joy.  

## Last Verse
<Put a short poem of your choice 8-20 lines,here>
